package vn.com.payment.entities;
// Generated 18-May-2021 09:19:42 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SubPermission generated by hbm2java
 */
@Entity
@Table(name = "sub_permission")
public class SubPermission implements java.io.Serializable {

	private Integer rowId;
	private String name;
	private int status;
	private int permissionId;
	private int orderMenu;
	private String alias;
	private String icon;

	public SubPermission() {
	}

	public SubPermission(String name, int status, int permissionId, int orderMenu, String alias, String icon) {
		this.name = name;
		this.status = status;
		this.permissionId = permissionId;
		this.orderMenu = orderMenu;
		this.alias = alias;
		this.icon = icon;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "row_id", unique = true, nullable = false)
	public Integer getRowId() {
		return this.rowId;
	}

	public void setRowId(Integer rowId) {
		this.rowId = rowId;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "permission_id", nullable = false)
	public int getPermissionId() {
		return this.permissionId;
	}

	public void setPermissionId(int permissionId) {
		this.permissionId = permissionId;
	}

	@Column(name = "order_menu", nullable = false)
	public int getOrderMenu() {
		return this.orderMenu;
	}

	public void setOrderMenu(int orderMenu) {
		this.orderMenu = orderMenu;
	}

	@Column(name = "alias", nullable = false, length = 200)
	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

	@Column(name = "icon", nullable = false, length = 20)
	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

}
