package vn.com.payment.entities;
// Generated Jun 22, 2021 1:26:46 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblBlackList generated by hbm2java
 */
@Entity
@Table(name = "tbl_black_list")
public class TblBlackList implements java.io.Serializable {

	private Integer blackListId;
	private int borrowerId;
	private Date escapeDate;
	private Integer entryStatus;
	private Date joinDate;
	private int groupDebtId;
	private Date effectiveDateFrom;
	private Date effectiveDateTo;
	private String borrowerName;
	private String borrowerIdNumber;

	public TblBlackList() {
	}

	public TblBlackList(int borrowerId, Date escapeDate, Date joinDate, int groupDebtId, Date effectiveDateFrom,
			Date effectiveDateTo, String borrowerName, String borrowerIdNumber) {
		this.borrowerId = borrowerId;
		this.escapeDate = escapeDate;
		this.joinDate = joinDate;
		this.groupDebtId = groupDebtId;
		this.effectiveDateFrom = effectiveDateFrom;
		this.effectiveDateTo = effectiveDateTo;
		this.borrowerName = borrowerName;
		this.borrowerIdNumber = borrowerIdNumber;
	}

	public TblBlackList(int borrowerId, Date escapeDate, Integer entryStatus, Date joinDate, int groupDebtId,
			Date effectiveDateFrom, Date effectiveDateTo, String borrowerName, String borrowerIdNumber) {
		this.borrowerId = borrowerId;
		this.escapeDate = escapeDate;
		this.entryStatus = entryStatus;
		this.joinDate = joinDate;
		this.groupDebtId = groupDebtId;
		this.effectiveDateFrom = effectiveDateFrom;
		this.effectiveDateTo = effectiveDateTo;
		this.borrowerName = borrowerName;
		this.borrowerIdNumber = borrowerIdNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "black_list_id", unique = true, nullable = false)
	public Integer getBlackListId() {
		return this.blackListId;
	}

	public void setBlackListId(Integer blackListId) {
		this.blackListId = blackListId;
	}

	@Column(name = "borrower_id", nullable = false)
	public int getBorrowerId() {
		return this.borrowerId;
	}

	public void setBorrowerId(int borrowerId) {
		this.borrowerId = borrowerId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "escape_date", nullable = false, length = 19)
	public Date getEscapeDate() {
		return this.escapeDate;
	}

	public void setEscapeDate(Date escapeDate) {
		this.escapeDate = escapeDate;
	}

	@Column(name = "entry_status")
	public Integer getEntryStatus() {
		return this.entryStatus;
	}

	public void setEntryStatus(Integer entryStatus) {
		this.entryStatus = entryStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "join_date", nullable = false, length = 19)
	public Date getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	@Column(name = "group_debt_id", nullable = false)
	public int getGroupDebtId() {
		return this.groupDebtId;
	}

	public void setGroupDebtId(int groupDebtId) {
		this.groupDebtId = groupDebtId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "effective_date_from", nullable = false, length = 10)
	public Date getEffectiveDateFrom() {
		return this.effectiveDateFrom;
	}

	public void setEffectiveDateFrom(Date effectiveDateFrom) {
		this.effectiveDateFrom = effectiveDateFrom;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "effective_date_to", nullable = false, length = 10)
	public Date getEffectiveDateTo() {
		return this.effectiveDateTo;
	}

	public void setEffectiveDateTo(Date effectiveDateTo) {
		this.effectiveDateTo = effectiveDateTo;
	}

	@Column(name = "borrower_name", nullable = false, length = 100)
	public String getBorrowerName() {
		return this.borrowerName;
	}

	public void setBorrowerName(String borrowerName) {
		this.borrowerName = borrowerName;
	}

	@Column(name = "borrower_id_number", nullable = false, length = 50)
	public String getBorrowerIdNumber() {
		return this.borrowerIdNumber;
	}

	public void setBorrowerIdNumber(String borrowerIdNumber) {
		this.borrowerIdNumber = borrowerIdNumber;
	}

}
