package vn.com.payment.entities;
// Generated 29-Jul-2021 21:48:37 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblDebtRemindHistory generated by hbm2java
 */
@Entity
@Table(name = "tbl_debt_remind_history", catalog = "db_fintech")
public class TblDebtRemindHistory implements java.io.Serializable {

	private Long rowId;
	private int loanId;
	private String loanCode;
	private Date createdDate;
	private String createdBy;
	private String adminRemark;
	private String borrowerRemark;
	private Integer remindType;

	public TblDebtRemindHistory() {
	}

	public TblDebtRemindHistory(int loanId, String loanCode) {
		this.loanId = loanId;
		this.loanCode = loanCode;
	}

	public TblDebtRemindHistory(int loanId, String loanCode, Date createdDate, String createdBy, String adminRemark,
			String borrowerRemark, Integer remindType) {
		this.loanId = loanId;
		this.loanCode = loanCode;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.adminRemark = adminRemark;
		this.borrowerRemark = borrowerRemark;
		this.remindType = remindType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "row_id", unique = true, nullable = false)
	public Long getRowId() {
		return this.rowId;
	}

	public void setRowId(Long rowId) {
		this.rowId = rowId;
	}

	@Column(name = "loan_id", nullable = false)
	public int getLoanId() {
		return this.loanId;
	}

	public void setLoanId(int loanId) {
		this.loanId = loanId;
	}

	@Column(name = "loan_code", nullable = false, length = 100)
	public String getLoanCode() {
		return this.loanCode;
	}

	public void setLoanCode(String loanCode) {
		this.loanCode = loanCode;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "admin_remark")
	public String getAdminRemark() {
		return this.adminRemark;
	}

	public void setAdminRemark(String adminRemark) {
		this.adminRemark = adminRemark;
	}

	@Column(name = "borrower_remark")
	public String getBorrowerRemark() {
		return this.borrowerRemark;
	}

	public void setBorrowerRemark(String borrowerRemark) {
		this.borrowerRemark = borrowerRemark;
	}

	@Column(name = "remind_type")
	public Integer getRemindType() {
		return this.remindType;
	}

	public void setRemindType(Integer remindType) {
		this.remindType = remindType;
	}

}
