package vn.com.payment.entities;
// Generated 25-Jul-2021 10:55:37 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblImages generated by hbm2java
 */
@Entity
@Table(name = "tbl_images")
public class TblImages implements java.io.Serializable {

	private Long imageId;
	private int loanRequestDetailId;
	private Integer imageType;
	private String imageByte;
	private String imageUrl;
	private Integer imageIsFront;
	private String imageName;
	private String partnerImageId;
	private Integer imageStatus;
	private Date deleteDate;
	private String imageInputName;
	private String uploadBy;
	private Integer billId;
	private Date createdDate;
	private Date editedDate;

	public TblImages() {
	}

	public TblImages(int loanRequestDetailId) {
		this.loanRequestDetailId = loanRequestDetailId;
	}

	public TblImages(int loanRequestDetailId, Integer imageType, String imageByte, String imageUrl,
			Integer imageIsFront, String imageName, String partnerImageId, Integer imageStatus, Date deleteDate,
			String imageInputName, String uploadBy, Integer billId, Date createdDate, Date editedDate) {
		this.loanRequestDetailId = loanRequestDetailId;
		this.imageType = imageType;
		this.imageByte = imageByte;
		this.imageUrl = imageUrl;
		this.imageIsFront = imageIsFront;
		this.imageName = imageName;
		this.partnerImageId = partnerImageId;
		this.imageStatus = imageStatus;
		this.deleteDate = deleteDate;
		this.imageInputName = imageInputName;
		this.uploadBy = uploadBy;
		this.billId = billId;
		this.createdDate = createdDate;
		this.editedDate = editedDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "image_id", unique = true, nullable = false)
	public Long getImageId() {
		return this.imageId;
	}

	public void setImageId(Long imageId) {
		this.imageId = imageId;
	}

	@Column(name = "loan_request_detail_id", nullable = false)
	public int getLoanRequestDetailId() {
		return this.loanRequestDetailId;
	}

	public void setLoanRequestDetailId(int loanRequestDetailId) {
		this.loanRequestDetailId = loanRequestDetailId;
	}

	@Column(name = "image_type")
	public Integer getImageType() {
		return this.imageType;
	}

	public void setImageType(Integer imageType) {
		this.imageType = imageType;
	}

	@Column(name = "image_byte")
	public String getImageByte() {
		return this.imageByte;
	}

	public void setImageByte(String imageByte) {
		this.imageByte = imageByte;
	}

	@Column(name = "image_url", length = 500)
	public String getImageUrl() {
		return this.imageUrl;
	}

	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	@Column(name = "image_is_front")
	public Integer getImageIsFront() {
		return this.imageIsFront;
	}

	public void setImageIsFront(Integer imageIsFront) {
		this.imageIsFront = imageIsFront;
	}

	@Column(name = "image_name")
	public String getImageName() {
		return this.imageName;
	}

	public void setImageName(String imageName) {
		this.imageName = imageName;
	}

	@Column(name = "partner_image_id", length = 150)
	public String getPartnerImageId() {
		return this.partnerImageId;
	}

	public void setPartnerImageId(String partnerImageId) {
		this.partnerImageId = partnerImageId;
	}

	@Column(name = "image_status")
	public Integer getImageStatus() {
		return this.imageStatus;
	}

	public void setImageStatus(Integer imageStatus) {
		this.imageStatus = imageStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "delete_date", length = 19)
	public Date getDeleteDate() {
		return this.deleteDate;
	}

	public void setDeleteDate(Date deleteDate) {
		this.deleteDate = deleteDate;
	}

	@Column(name = "image_input_name")
	public String getImageInputName() {
		return this.imageInputName;
	}

	public void setImageInputName(String imageInputName) {
		this.imageInputName = imageInputName;
	}

	@Column(name = "upload_by")
	public String getUploadBy() {
		return this.uploadBy;
	}

	public void setUploadBy(String uploadBy) {
		this.uploadBy = uploadBy;
	}

	@Column(name = "bill_id")
	public Integer getBillId() {
		return this.billId;
	}

	public void setBillId(Integer billId) {
		this.billId = billId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "edited_date", length = 19)
	public Date getEditedDate() {
		return this.editedDate;
	}

	public void setEditedDate(Date editedDate) {
		this.editedDate = editedDate;
	}

}
