package vn.com.payment.entities;
// Generated 21-Jun-2021 11:08:17 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblInbox generated by hbm2java
 */
@Entity
@Table(name = "tbl_inbox")
public class TblInbox implements java.io.Serializable {

	private Integer inboxId;
	private String username;
	private Date createdDate;
	private int inboxStatus;
	private Integer inboxRead;
	private String shortDesc;
	private String content;
	private String url;
	private Integer actionType;
	private Date readDate;
	private Integer loanId;
	private Integer loanStatus;
	private String loanCode;

	public TblInbox() {
	}

	public TblInbox(int inboxStatus) {
		this.inboxStatus = inboxStatus;
	}

	public TblInbox(String username, Date createdDate, int inboxStatus, Integer inboxRead, String shortDesc,
			String content, String url, Integer actionType, Date readDate, Integer loanId, Integer loanStatus,
			String loanCode) {
		this.username = username;
		this.createdDate = createdDate;
		this.inboxStatus = inboxStatus;
		this.inboxRead = inboxRead;
		this.shortDesc = shortDesc;
		this.content = content;
		this.url = url;
		this.actionType = actionType;
		this.readDate = readDate;
		this.loanId = loanId;
		this.loanStatus = loanStatus;
		this.loanCode = loanCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "inbox_id", unique = true, nullable = false)
	public Integer getInboxId() {
		return this.inboxId;
	}

	public void setInboxId(Integer inboxId) {
		this.inboxId = inboxId;
	}

	@Column(name = "username")
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "inbox_status", nullable = false)
	public int getInboxStatus() {
		return this.inboxStatus;
	}

	public void setInboxStatus(int inboxStatus) {
		this.inboxStatus = inboxStatus;
	}

	@Column(name = "inbox_read")
	public Integer getInboxRead() {
		return this.inboxRead;
	}

	public void setInboxRead(Integer inboxRead) {
		this.inboxRead = inboxRead;
	}

	@Column(name = "short_desc")
	public String getShortDesc() {
		return this.shortDesc;
	}

	public void setShortDesc(String shortDesc) {
		this.shortDesc = shortDesc;
	}

	@Column(name = "content", length = 1000)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "action_type")
	public Integer getActionType() {
		return this.actionType;
	}

	public void setActionType(Integer actionType) {
		this.actionType = actionType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "read_date", length = 19)
	public Date getReadDate() {
		return this.readDate;
	}

	public void setReadDate(Date readDate) {
		this.readDate = readDate;
	}

	@Column(name = "loan_id")
	public Integer getLoanId() {
		return this.loanId;
	}

	public void setLoanId(Integer loanId) {
		this.loanId = loanId;
	}

	@Column(name = "loan_status")
	public Integer getLoanStatus() {
		return this.loanStatus;
	}

	public void setLoanStatus(Integer loanStatus) {
		this.loanStatus = loanStatus;
	}

	@Column(name = "loan_code")
	public String getLoanCode() {
		return this.loanCode;
	}

	public void setLoanCode(String loanCode) {
		this.loanCode = loanCode;
	}

}
