package vn.com.payment.entities;
// Generated 01-Jul-2021 15:31:52 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblInsuranceProviders generated by hbm2java
 */
@Entity
@Table(name = "tbl_insurance_providers", catalog = "db_fintech")
public class TblInsuranceProviders implements java.io.Serializable {

	private Long insuranceProviderId;
	private String insuranceCode;
	private String insuranceName;
	private Integer activeStt;
	private Date createdDate;
	private Date editedDate;
	private Integer fixFee;
	private Float fixRate;
	private String insuranceApi;
	private String authToken;
	private String apiAcc;
	private String apiPass;
	private String authTokenExpires;
	private Integer insuranceDefault;

	public TblInsuranceProviders() {
	}

	public TblInsuranceProviders(String insuranceCode, String insuranceName, Integer activeStt, Date createdDate,
			Date editedDate, Integer fixFee, Float fixRate, String insuranceApi, String authToken, String apiAcc,
			String apiPass, String authTokenExpires, Integer insuranceDefault) {
		this.insuranceCode = insuranceCode;
		this.insuranceName = insuranceName;
		this.activeStt = activeStt;
		this.createdDate = createdDate;
		this.editedDate = editedDate;
		this.fixFee = fixFee;
		this.fixRate = fixRate;
		this.insuranceApi = insuranceApi;
		this.authToken = authToken;
		this.apiAcc = apiAcc;
		this.apiPass = apiPass;
		this.authTokenExpires = authTokenExpires;
		this.insuranceDefault = insuranceDefault;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "insurance_provider_id", unique = true, nullable = false)
	public Long getInsuranceProviderId() {
		return this.insuranceProviderId;
	}

	public void setInsuranceProviderId(Long insuranceProviderId) {
		this.insuranceProviderId = insuranceProviderId;
	}

	@Column(name = "insurance_code")
	public String getInsuranceCode() {
		return this.insuranceCode;
	}

	public void setInsuranceCode(String insuranceCode) {
		this.insuranceCode = insuranceCode;
	}

	@Column(name = "insurance_name")
	public String getInsuranceName() {
		return this.insuranceName;
	}

	public void setInsuranceName(String insuranceName) {
		this.insuranceName = insuranceName;
	}

	@Column(name = "active_stt")
	public Integer getActiveStt() {
		return this.activeStt;
	}

	public void setActiveStt(Integer activeStt) {
		this.activeStt = activeStt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "edited_date", length = 19)
	public Date getEditedDate() {
		return this.editedDate;
	}

	public void setEditedDate(Date editedDate) {
		this.editedDate = editedDate;
	}

	@Column(name = "fix_fee")
	public Integer getFixFee() {
		return this.fixFee;
	}

	public void setFixFee(Integer fixFee) {
		this.fixFee = fixFee;
	}

	@Column(name = "fix_rate", precision = 12, scale = 0)
	public Float getFixRate() {
		return this.fixRate;
	}

	public void setFixRate(Float fixRate) {
		this.fixRate = fixRate;
	}

	@Column(name = "insurance_api")
	public String getInsuranceApi() {
		return this.insuranceApi;
	}

	public void setInsuranceApi(String insuranceApi) {
		this.insuranceApi = insuranceApi;
	}

	@Column(name = "auth_token")
	public String getAuthToken() {
		return this.authToken;
	}

	public void setAuthToken(String authToken) {
		this.authToken = authToken;
	}

	@Column(name = "api_acc")
	public String getApiAcc() {
		return this.apiAcc;
	}

	public void setApiAcc(String apiAcc) {
		this.apiAcc = apiAcc;
	}

	@Column(name = "api_pass")
	public String getApiPass() {
		return this.apiPass;
	}

	public void setApiPass(String apiPass) {
		this.apiPass = apiPass;
	}

	@Column(name = "auth_token_expires")
	public String getAuthTokenExpires() {
		return this.authTokenExpires;
	}

	public void setAuthTokenExpires(String authTokenExpires) {
		this.authTokenExpires = authTokenExpires;
	}

	@Column(name = "insurance_default")
	public Integer getInsuranceDefault() {
		return this.insuranceDefault;
	}

	public void setInsuranceDefault(Integer insuranceDefault) {
		this.insuranceDefault = insuranceDefault;
	}

}
