package vn.com.payment.entities;
// Generated Jun 20, 2021 1:41:07 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TblInsuranceBanks generated by hbm2java
 */
@Entity
@Table(name = "tbl_insurance_banks", catalog = "db_fintech")
public class TblInsuranceBanks implements java.io.Serializable {

	private Integer mappingId;
	private int insuranceProviderId;
	private String bankCode;
	private String accBankName;
	private String accBankNo;
	private Integer activeStt;
	private Integer fixFee;
	private Float fixRate;
	private Integer bankCodeType;
	private String bankName;

	public TblInsuranceBanks() {
	}

	public TblInsuranceBanks(int insuranceProviderId, String bankCode) {
		this.insuranceProviderId = insuranceProviderId;
		this.bankCode = bankCode;
	}

	public TblInsuranceBanks(int insuranceProviderId, String bankCode, String accBankName, String accBankNo,
			Integer activeStt, Integer fixFee, Float fixRate, Integer bankCodeType, String bankName) {
		this.insuranceProviderId = insuranceProviderId;
		this.bankCode = bankCode;
		this.accBankName = accBankName;
		this.accBankNo = accBankNo;
		this.activeStt = activeStt;
		this.fixFee = fixFee;
		this.fixRate = fixRate;
		this.bankCodeType = bankCodeType;
		this.bankName = bankName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mapping_id", unique = true, nullable = false)
	public Integer getMappingId() {
		return this.mappingId;
	}

	public void setMappingId(Integer mappingId) {
		this.mappingId = mappingId;
	}

	@Column(name = "insurance_provider_id", nullable = false)
	public int getInsuranceProviderId() {
		return this.insuranceProviderId;
	}

	public void setInsuranceProviderId(int insuranceProviderId) {
		this.insuranceProviderId = insuranceProviderId;
	}

	@Column(name = "bank_code", nullable = false, length = 50)
	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	@Column(name = "acc_bank_name", length = 200)
	public String getAccBankName() {
		return this.accBankName;
	}

	public void setAccBankName(String accBankName) {
		this.accBankName = accBankName;
	}

	@Column(name = "acc_bank_no", length = 100)
	public String getAccBankNo() {
		return this.accBankNo;
	}

	public void setAccBankNo(String accBankNo) {
		this.accBankNo = accBankNo;
	}

	@Column(name = "active_stt")
	public Integer getActiveStt() {
		return this.activeStt;
	}

	public void setActiveStt(Integer activeStt) {
		this.activeStt = activeStt;
	}

	@Column(name = "fix_fee")
	public Integer getFixFee() {
		return this.fixFee;
	}

	public void setFixFee(Integer fixFee) {
		this.fixFee = fixFee;
	}

	@Column(name = "fix_rate", precision = 12, scale = 0)
	public Float getFixRate() {
		return this.fixRate;
	}

	public void setFixRate(Float fixRate) {
		this.fixRate = fixRate;
	}

	@Column(name = "bank_code_type")
	public Integer getBankCodeType() {
		return this.bankCodeType;
	}

	public void setBankCodeType(Integer bankCodeType) {
		this.bankCodeType = bankCodeType;
	}

	@Column(name = "bank_name")
	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

}
