package vn.com.payment.entities;
// Generated Jun 18, 2021 12:35:32 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblSponsor generated by hbm2java
 */
@Entity
@Table(name = "tbl_sponsor")
public class TblSponsor implements java.io.Serializable {

	private Integer sponsorId;
	private String sponsorName;
	private String sponsorMobile;
	private int sponsorStatus;
	private Date deactiveDate;
	private String description;
	private Date createdDate;
	private String sponsorMobile2;
	private String sponsorAddress;
	private String sponsorEmail;
	private String sponsorIdNumber;
	private String sponsorIdIssuedBy;
	private Date sponsorIdIssuedDate;
	private int sponsorAccountId;
	private String sponsorProvinceName;
	private String sponsorBankAccount;
	private String sponsorBankName;
	private String sponsorBankBranch;
	private String sponsorInvestmentCommitment;
	private int sponsorType;
	private int sponsorInvestmentType;
	private String sponsorCode;
	private String sponsorEnName;
	private Long totalDisbursement;
	private Long totalSettlement;

	public TblSponsor() {
	}

	public TblSponsor(String sponsorName, String sponsorMobile, int sponsorStatus, Date deactiveDate, Date createdDate,
			String sponsorMobile2, String sponsorAddress, String sponsorEmail, String sponsorIdNumber,
			String sponsorIdIssuedBy, Date sponsorIdIssuedDate, int sponsorAccountId, String sponsorProvinceName,
			String sponsorBankAccount, String sponsorBankName, String sponsorBankBranch,
			String sponsorInvestmentCommitment, int sponsorType, int sponsorInvestmentType, String sponsorCode) {
		this.sponsorName = sponsorName;
		this.sponsorMobile = sponsorMobile;
		this.sponsorStatus = sponsorStatus;
		this.deactiveDate = deactiveDate;
		this.createdDate = createdDate;
		this.sponsorMobile2 = sponsorMobile2;
		this.sponsorAddress = sponsorAddress;
		this.sponsorEmail = sponsorEmail;
		this.sponsorIdNumber = sponsorIdNumber;
		this.sponsorIdIssuedBy = sponsorIdIssuedBy;
		this.sponsorIdIssuedDate = sponsorIdIssuedDate;
		this.sponsorAccountId = sponsorAccountId;
		this.sponsorProvinceName = sponsorProvinceName;
		this.sponsorBankAccount = sponsorBankAccount;
		this.sponsorBankName = sponsorBankName;
		this.sponsorBankBranch = sponsorBankBranch;
		this.sponsorInvestmentCommitment = sponsorInvestmentCommitment;
		this.sponsorType = sponsorType;
		this.sponsorInvestmentType = sponsorInvestmentType;
		this.sponsorCode = sponsorCode;
	}

	public TblSponsor(String sponsorName, String sponsorMobile, int sponsorStatus, Date deactiveDate,
			String description, Date createdDate, String sponsorMobile2, String sponsorAddress, String sponsorEmail,
			String sponsorIdNumber, String sponsorIdIssuedBy, Date sponsorIdIssuedDate, int sponsorAccountId,
			String sponsorProvinceName, String sponsorBankAccount, String sponsorBankName, String sponsorBankBranch,
			String sponsorInvestmentCommitment, int sponsorType, int sponsorInvestmentType, String sponsorCode,
			String sponsorEnName, Long totalDisbursement, Long totalSettlement) {
		this.sponsorName = sponsorName;
		this.sponsorMobile = sponsorMobile;
		this.sponsorStatus = sponsorStatus;
		this.deactiveDate = deactiveDate;
		this.description = description;
		this.createdDate = createdDate;
		this.sponsorMobile2 = sponsorMobile2;
		this.sponsorAddress = sponsorAddress;
		this.sponsorEmail = sponsorEmail;
		this.sponsorIdNumber = sponsorIdNumber;
		this.sponsorIdIssuedBy = sponsorIdIssuedBy;
		this.sponsorIdIssuedDate = sponsorIdIssuedDate;
		this.sponsorAccountId = sponsorAccountId;
		this.sponsorProvinceName = sponsorProvinceName;
		this.sponsorBankAccount = sponsorBankAccount;
		this.sponsorBankName = sponsorBankName;
		this.sponsorBankBranch = sponsorBankBranch;
		this.sponsorInvestmentCommitment = sponsorInvestmentCommitment;
		this.sponsorType = sponsorType;
		this.sponsorInvestmentType = sponsorInvestmentType;
		this.sponsorCode = sponsorCode;
		this.sponsorEnName = sponsorEnName;
		this.totalDisbursement = totalDisbursement;
		this.totalSettlement = totalSettlement;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "sponsor_id", unique = true, nullable = false)
	public Integer getSponsorId() {
		return this.sponsorId;
	}

	public void setSponsorId(Integer sponsorId) {
		this.sponsorId = sponsorId;
	}

	@Column(name = "sponsor_name", nullable = false, length = 100)
	public String getSponsorName() {
		return this.sponsorName;
	}

	public void setSponsorName(String sponsorName) {
		this.sponsorName = sponsorName;
	}

	@Column(name = "sponsor_mobile", nullable = false, length = 20)
	public String getSponsorMobile() {
		return this.sponsorMobile;
	}

	public void setSponsorMobile(String sponsorMobile) {
		this.sponsorMobile = sponsorMobile;
	}

	@Column(name = "sponsor_status", nullable = false)
	public int getSponsorStatus() {
		return this.sponsorStatus;
	}

	public void setSponsorStatus(int sponsorStatus) {
		this.sponsorStatus = sponsorStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deactive_date", nullable = false, length = 19)
	public Date getDeactiveDate() {
		return this.deactiveDate;
	}

	public void setDeactiveDate(Date deactiveDate) {
		this.deactiveDate = deactiveDate;
	}

	@Column(name = "description", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "sponsor_mobile_2", nullable = false, length = 15)
	public String getSponsorMobile2() {
		return this.sponsorMobile2;
	}

	public void setSponsorMobile2(String sponsorMobile2) {
		this.sponsorMobile2 = sponsorMobile2;
	}

	@Column(name = "sponsor_address", nullable = false, length = 200)
	public String getSponsorAddress() {
		return this.sponsorAddress;
	}

	public void setSponsorAddress(String sponsorAddress) {
		this.sponsorAddress = sponsorAddress;
	}

	@Column(name = "sponsor_email", nullable = false, length = 200)
	public String getSponsorEmail() {
		return this.sponsorEmail;
	}

	public void setSponsorEmail(String sponsorEmail) {
		this.sponsorEmail = sponsorEmail;
	}

	@Column(name = "sponsor_id_number", nullable = false, length = 20)
	public String getSponsorIdNumber() {
		return this.sponsorIdNumber;
	}

	public void setSponsorIdNumber(String sponsorIdNumber) {
		this.sponsorIdNumber = sponsorIdNumber;
	}

	@Column(name = "sponsor_id_issued_by", nullable = false, length = 200)
	public String getSponsorIdIssuedBy() {
		return this.sponsorIdIssuedBy;
	}

	public void setSponsorIdIssuedBy(String sponsorIdIssuedBy) {
		this.sponsorIdIssuedBy = sponsorIdIssuedBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "sponsor_id_issued_date", nullable = false, length = 10)
	public Date getSponsorIdIssuedDate() {
		return this.sponsorIdIssuedDate;
	}

	public void setSponsorIdIssuedDate(Date sponsorIdIssuedDate) {
		this.sponsorIdIssuedDate = sponsorIdIssuedDate;
	}

	@Column(name = "sponsor_account_id", nullable = false)
	public int getSponsorAccountId() {
		return this.sponsorAccountId;
	}

	public void setSponsorAccountId(int sponsorAccountId) {
		this.sponsorAccountId = sponsorAccountId;
	}

	@Column(name = "sponsor_province_name", nullable = false, length = 100)
	public String getSponsorProvinceName() {
		return this.sponsorProvinceName;
	}

	public void setSponsorProvinceName(String sponsorProvinceName) {
		this.sponsorProvinceName = sponsorProvinceName;
	}

	@Column(name = "sponsor_bank_account", nullable = false, length = 100)
	public String getSponsorBankAccount() {
		return this.sponsorBankAccount;
	}

	public void setSponsorBankAccount(String sponsorBankAccount) {
		this.sponsorBankAccount = sponsorBankAccount;
	}

	@Column(name = "sponsor_bank_name", nullable = false, length = 100)
	public String getSponsorBankName() {
		return this.sponsorBankName;
	}

	public void setSponsorBankName(String sponsorBankName) {
		this.sponsorBankName = sponsorBankName;
	}

	@Column(name = "sponsor_bank_branch", nullable = false, length = 100)
	public String getSponsorBankBranch() {
		return this.sponsorBankBranch;
	}

	public void setSponsorBankBranch(String sponsorBankBranch) {
		this.sponsorBankBranch = sponsorBankBranch;
	}

	@Column(name = "sponsor_investment_commitment", nullable = false, length = 100)
	public String getSponsorInvestmentCommitment() {
		return this.sponsorInvestmentCommitment;
	}

	public void setSponsorInvestmentCommitment(String sponsorInvestmentCommitment) {
		this.sponsorInvestmentCommitment = sponsorInvestmentCommitment;
	}

	@Column(name = "sponsor_type", nullable = false)
	public int getSponsorType() {
		return this.sponsorType;
	}

	public void setSponsorType(int sponsorType) {
		this.sponsorType = sponsorType;
	}

	@Column(name = "sponsor_investment_type", nullable = false)
	public int getSponsorInvestmentType() {
		return this.sponsorInvestmentType;
	}

	public void setSponsorInvestmentType(int sponsorInvestmentType) {
		this.sponsorInvestmentType = sponsorInvestmentType;
	}

	@Column(name = "sponsor_code", nullable = false, length = 50)
	public String getSponsorCode() {
		return this.sponsorCode;
	}

	public void setSponsorCode(String sponsorCode) {
		this.sponsorCode = sponsorCode;
	}

	@Column(name = "sponsor_en_name")
	public String getSponsorEnName() {
		return this.sponsorEnName;
	}

	public void setSponsorEnName(String sponsorEnName) {
		this.sponsorEnName = sponsorEnName;
	}

	@Column(name = "total_disbursement", precision = 10, scale = 0)
	public Long getTotalDisbursement() {
		return this.totalDisbursement;
	}

	public void setTotalDisbursement(Long totalDisbursement) {
		this.totalDisbursement = totalDisbursement;
	}

	@Column(name = "total_settlement", precision = 10, scale = 0)
	public Long getTotalSettlement() {
		return this.totalSettlement;
	}

	public void setTotalSettlement(Long totalSettlement) {
		this.totalSettlement = totalSettlement;
	}

}
