package vn.com.payment.entities;
// Generated Jun 22, 2021 1:26:46 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TblSystemActions generated by hbm2java
 */
@Entity
@Table(name = "tbl_system_actions", catalog = "db_fintech")
public class TblSystemActions implements java.io.Serializable {

	private Long actionId;
	private String actionType;
	private Date registerDate;
	private String actionData;
	private Integer rootId;
	private Integer subObjectId;
	private String responseData;

	public TblSystemActions() {
	}

	public TblSystemActions(String actionType, String actionData) {
		this.actionType = actionType;
		this.actionData = actionData;
	}

	public TblSystemActions(String actionType, Date registerDate, String actionData, Integer rootId,
			Integer subObjectId, String responseData) {
		this.actionType = actionType;
		this.registerDate = registerDate;
		this.actionData = actionData;
		this.rootId = rootId;
		this.subObjectId = subObjectId;
		this.responseData = responseData;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "action_id", unique = true, nullable = false)
	public Long getActionId() {
		return this.actionId;
	}

	public void setActionId(Long actionId) {
		this.actionId = actionId;
	}

	@Column(name = "action_type", nullable = false, length = 100)
	public String getActionType() {
		return this.actionType;
	}

	public void setActionType(String actionType) {
		this.actionType = actionType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "register_date", length = 19)
	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}

	@Column(name = "action_data", nullable = false)
	public String getActionData() {
		return this.actionData;
	}

	public void setActionData(String actionData) {
		this.actionData = actionData;
	}

	@Column(name = "root_id")
	public Integer getRootId() {
		return this.rootId;
	}

	public void setRootId(Integer rootId) {
		this.rootId = rootId;
	}

	@Column(name = "sub_object_id")
	public Integer getSubObjectId() {
		return this.subObjectId;
	}

	public void setSubObjectId(Integer subObjectId) {
		this.subObjectId = subObjectId;
	}

	@Column(name = "response_data")
	public String getResponseData() {
		return this.responseData;
	}

	public void setResponseData(String responseData) {
		this.responseData = responseData;
	}

}
